### ISSUE TITLE
Cant buy a jerrycan

### ISSUE THREAD

**Issue by Patrickstek121** [loljoshie/lj-fuel#17]
Hello,

I got this script but when i would buy a jerrycan there is nothing shows up with the target eye

![image](https://user-images.githubusercontent.com/16652731/153200730-2974550b-7364-4f0a-b304-5088834cacdb.png)

**Comment by f9ariel** [comment]
try to put the EXPORT qb target on 

CreateThread(function()
          qtarget export here
end)

so that it will be fix :) dont forget to hit me a thanks if it works :) 👍

**Comment by WhiskeyFiveOne** [comment]
i am having this issue as well could someone please paste the code needed for this thank you
