### ISSUE TITLE
BUG: unlimited jerrycan ammo when you have more than 1 jerrycan

### ISSUE THREAD

**Issue by skizmx** [loljoshie/lj-fuel#20]
if you have 2 or more jerrycan, when you switch from empty jerrycan to full jerrycan, the empty jerrycan will be filled again

**Comment by nukestarz** [comment]
yeah that's my issue too

**Comment by GeekHamza1** [comment]
same here but i only have one jerrycan

**Comment by firinggamers** [comment]
did u guys fix this issue?

**Comment by firinggamers** [comment]
> if you have 2 or more jerrycan, when you switch from empty jerrycan to full jerrycan, the empty jerrycan will be filled again

i think the new pullreq has fixed this issue
