### ISSUE TITLE
Negative cost

### ISSUE THREAD

**Issue by TonybynMp4** [loljoshie/lj-fuel#21]
![image](https://user-images.githubusercontent.com/97451137/156578133-1bbadbd7-e616-4887-8e77-a767b2cefeb0.png)
I don't know why but the cost seems to be in negative above a certain level of fuel causing the player to not pay anything at all,
The price do becomes a positive again under a certain level of fuel.
btw i don't know if it's your script or just QBcore but when i make a car leak fuel and get into it it automatically stops to leak wich is a bit annoying (to me at least)

**Comment by Insaneshane99** [comment]
read my last comments in https://github.com/loljoshie/lj-fuel/issues/18 , I had the issue your explaining and picturing ,  Do not put Config.RefillCost = 100 below 100 it will break the price calculations

**Comment by TonybynMp4** [comment]
oh ok thanks !
