### ISSUE TITLE
haveing issue when you fir to fuel

### ISSUE THREAD

**Issue by Muri22** [loljoshie/lj-fuel#22]
hi i have a issue white lj-fuel when some fire the fuel in the ground the weapon break after shoting it https://cdn.discordapp.com/attachments/900180032935325707/951641894734147614/Desktop_2022.03.11_-_01.39.04.01_Trim.mp4

**Comment by d-w00d** [comment]
believe this is an issue with qb-weapons as it handles weapon durabilities. Not LJ-fuel

**Comment by Muri22** [comment]
it fine with legacyfuel only with lj have this issue
