### ISSUE TITLE
Some pumps not working and other pumps in different language?

### ISSUE THREAD

**Issue by FirefighterKyle** [loljoshie/lj-fuel#24]
So at the pumps in Sandy it doesn't take my money, but it also doesn't fuel my vehicle at all? It goes through the progress bar and the animation of fueling, but doesn't do anything? At the pumps by flying wheels it is in Dutch or something which is very confusing? I checked all my folders to make sure legacy fuel was changed to lj-fuel. Everything on my side seems to correct, but Sandy pumps doesn't work and the one down the road is in Dutch?

**Comment by MG79NC** [comment]
same issue for me all the pumps in Sandy cost 0 but it does actually fill my cars for free
