### ISSUE TITLE
Refueling does not work when people are still in the vehicle

### ISSUE THREAD

**Issue by TweakyGaming** [loljoshie/lj-fuel#25]
Refueling does not work when people are still in the vehicle, only the last person to leave the vehicle can refuel.

**Comment by helenclarko** [comment]
This is likely a vehicle ownership issue. I've had the same problem with vehicle keys. Unable to lock a vehicle unless you are the last one out of it.
Odd that it can't assign ownership when someone else is in the vehicle... And on top of that, you shouldn't be restricted by the fact someone else is in the car... Let me check to see whats going on.
