### ISSUE TITLE
Not all vehices keep running after player exits

### ISSUE THREAD

**Issue by Swyper0703** [loljoshie/lj-fuel#6]
Hi,

I'm having issues with:

`Config.LeaveEngineRunning = true`

& 

`if Config.LeaveEngineRunning then
Citizen.CreateThread(function()
	while true do
		Citizen.Wait(100)
		local ped = GetPlayerPed(-1)
if DoesEntityExist(ped) and IsPedInAnyVehicle(ped, false) and IsControlPressed(2, 75) and not IsEntityDead(ped) and not IsPauseMenuActive() then
			local engineWasRunning = GetIsVehicleEngineRunning(GetVehiclePedIsIn(ped, true))
			Citizen.Wait(1000)
			if DoesEntityExist(ped) and not IsPedInAnyVehicle(ped, false) and not IsEntityDead(ped) and not IsPauseMenuActive() then
				local veh = GetVehiclePedIsIn(ped, true)
				if engineWasRunning then
					SetVehicleEngineOn(veh, true, true, true)
				end
			end
		end
	end
end)
end`

When trying out different vehicles I noticed that most cars in the super/sports category turn off when players exit vehicle however for compacts & sedans it is working as expected.

Could you please point me in the direction of the issue?

Many Thanks,

**Comment by loljoshie** [comment]
Is anyone else able to verify that this is happening?
